import type { VisualStyle } from '@/types';
import { buildCompactImageCaptureContract } from './promptArchitecture';

function clipAtWord(value: string, maxLength: number): string {
  if (value.length <= maxLength) return value;
  const candidate = value.slice(0, Math.max(1, maxLength - 3));
  const boundary = candidate.lastIndexOf(' ');
  return `${(boundary >= maxLength * 0.68 ? candidate.slice(0, boundary) : candidate).trimEnd()}...`;
}

// Split a 3x3 grid image into 9 individual images using Canvas
// Each cell has the same aspect ratio as the whole grid
export function chunkGridBatch<T>(items: T[], size = 9): T[][] {
  if (!Number.isInteger(size) || size < 1) throw new Error('Grid batch size must be a positive integer');
  const batches: T[][] = [];
  for (let index = 0; index < items.length; index += size) {
    batches.push(items.slice(index, index + size));
  }
  return batches;
}

export async function splitGridImage(
  imageUrl: string,
  aspectRatio: '16:9' | '9:16' | '1:1' = '16:9'
): Promise<string[]> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const cellWidth = Math.floor(img.width / 3);
      const cellHeight = Math.floor(img.height / 3);
      // Inset to skip border/separator pixels generated by AI
      const inset = Math.max(0, Math.round(Math.min(cellWidth, cellHeight) * 0.045)); // ~1.5% of full width
      const cells: string[] = [];

      try {
        for (let row = 0; row < 3; row++) {
          for (let col = 0; col < 3; col++) {
            const sx = col * cellWidth + inset;
            const sy = row * cellHeight + inset;
            const sw = cellWidth - inset * 2;
            const sh = cellHeight - inset * 2;
            const canvas = document.createElement('canvas');
            canvas.width = sw;
            canvas.height = sh;
            const ctx = canvas.getContext('2d');
            if (!ctx) throw new Error('Failed to get canvas context');
            ctx.drawImage(img, sx, sy, sw, sh, 0, 0, sw, sh);
            cells.push(canvas.toDataURL('image/jpeg', 0.95));
          }
        }
        resolve(cells);
      } catch (error) {
        reject(error instanceof Error ? error : new Error('Failed to split grid image'));
      }
    };
    img.onerror = () => reject(new Error('Failed to load grid image'));
    img.src = imageUrl.startsWith('data:')
      ? imageUrl
      : `/api/proxy-image?url=${encodeURIComponent(imageUrl)}`;
  });
}

// Build the 3x3 grid prompt for a given set of storyboards
export function buildGridPrompt(
  sceneStyle: string,
  characterDescriptions: string,
  shotDescriptions: string[],
  aspectRatio: '16:9' | '9:16' | '1:1',
  referenceImageLabels?: string[], // e.g. ['TOTODA (ref image 1)', 'MOMODA (ref image 2)']
  sceneNumbers?: Array<number | string>,
  visualStyle?: VisualStyle,
): string {
  const GRID_PROMPT_BUDGET = 3500;
  const PANEL_PROMPT_BUDGET = 180;
  const orientation = aspectRatio === '9:16' ? 'vertical portrait' : aspectRatio === '1:1' ? 'square' : 'horizontal landscape';
  const shots = shotDescriptions.slice(0, 9).map(shot => {
    const requirementIndex = Math.max(shot.indexOf('CAST['), shot.indexOf('REQUIRED CHARACTERS'));
    if (requirementIndex === -1) return clipAtWord(shot, 160);
    if (shot.length <= PANEL_PROMPT_BUDGET) return shot;
    const requirements = shot.slice(requirementIndex);
    const visualBudget = Math.max(90, PANEL_PROMPT_BUDGET - requirements.length - 1);
    return `${clipAtWord(shot.slice(0, requirementIndex).trim(), visualBudget)} ${requirements}`;
  });
  while (shots.length < 9) shots.push(shots[shots.length - 1] || 'medium shot');

  const refSection = referenceImageLabels && referenceImageLabels.length > 0
    ? `Reference mapping: ${referenceImageLabels.map((label, i) => `#${i + 1}=${label}`).join('; ').slice(0, 340)}`
    : '';

  const normalizedSceneNumbers = shots.map((_, index) => sceneNumbers?.[index] ?? index + 1);
  const batchId = normalizedSceneNumbers.map(String).join('-');
  const panelSection = shots
    .map((shot, index) => `Panel ${index + 1} (story scene ${normalizedSceneNumbers[index]}): ${shot}`)
    .join('\n');

  // Put the batch identity and all nine shot descriptions first. The APIMart
  // image endpoint has a practical prompt limit, so any defensive truncation
  // must remove secondary continuity prose rather than the content that makes
  // this grid different from the previous/next batch.
  const prompt = `UNIQUE STORYBOARD BATCH: ${batchId}
${buildCompactImageCaptureContract(visualStyle)}
${refSection}

CAST AUTHORITY: each panel's EXACT CAST count/list in CAST[n] is authoritative. Show each listed identity exactly once; no omission, merge, clone, sheet-layout copy, reflection-double or extra. Character sheets prove one identity only. No captions, subtitles, speech bubbles, labels, logos, watermark or readable text.

Render these nine distinct moments in exact order:
${panelSection}

Generate one 3x3 cinematic storyboard contact sheet. Each panel is ${orientation} (${aspectRatio}). Arrange panels left-to-right, top-to-bottom with no borders, gaps, separator lines, labels, captions, or text.

Scene continuity: ${sceneStyle.slice(0, 180)}
Character identities (match mapped references exactly wherever they appear):
${characterDescriptions.slice(0, 300)}

CRITICAL CAST RULES:
- Each panel's EXACT CAST count is authoritative; never infer the batch-wide reference list as every panel's cast.
- Character sheets prove one identity only. Animals are full characters and must retain species, markings and scale.
- No captions, subtitles, dialogue text, speech bubbles, panel labels, logos, watermark, or readable text.

Keep the established source positions, color temperature and environment continuous while allowing physically correct angle-dependent shadows, highlights and depth. Every cell is a complete standalone composition.`;

  // All nine panels and the authoritative capture/cast rules are intentionally
  // placed first. Only repeated continuity prose at the tail may be removed.
  return prompt.length <= GRID_PROMPT_BUDGET
    ? prompt
    : prompt.slice(0, GRID_PROMPT_BUDGET).trimEnd();
}
